// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1170u10CzKs4O4wO6gKPqCtzzWQAJmJs',
    appId: '1:225967324567:web:55d19d6eceab425509d8d2',
    messagingSenderId: '225967324567',
    projectId: 'contract-us-a7465',
    authDomain: 'contract-us-a7465.firebaseapp.com',
    storageBucket: 'contract-us-a7465.appspot.com',
    measurementId: 'G-KMY0M07XBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2SiXaYNKfGgDWWp1K0kJkImdGcZ-z9Ew',
    appId: '1:225967324567:android:7441a6eaa858d90709d8d2',
    messagingSenderId: '225967324567',
    projectId: 'contract-us-a7465',
    storageBucket: 'contract-us-a7465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAtishePS3l5SRlam1AjoS5VHrNGOewuw',
    appId: '1:225967324567:ios:bbe4d1ac294853d309d8d2',
    messagingSenderId: '225967324567',
    projectId: 'contract-us-a7465',
    storageBucket: 'contract-us-a7465.appspot.com',
    iosBundleId: 'com.ContractusLLC.contractus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAtishePS3l5SRlam1AjoS5VHrNGOewuw',
    appId: '1:225967324567:ios:d675a66018fbd80509d8d2',
    messagingSenderId: '225967324567',
    projectId: 'contract-us-a7465',
    storageBucket: 'contract-us-a7465.appspot.com',
    iosBundleId: 'com.ContractusLLC.contractus.RunnerTests',
  );
}
